// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "mall/apps/app/api/internal/handler/user"
	"mall/apps/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user_register",
				Handler: user.RegisterHandleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/front_user_login",
				Handler: user.LoginHandleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send_email",
				Handler: user.SendEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin_login",
				Handler: user.AdminLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)
}
