// Code generated by goctl. DO NOT EDIT.
package types

type SendEmailRequest struct {
	Email string `json:"email"`
}

type SendEmailResponse struct {
	Code string `json:"code"`
	Msg  string `json:"msg"`
}

type RegisterRequest struct {
	Email      string `form:"email"`
	Catpche    string `form:"catpche"`
	Password   string `form:"password"`
	Repassword string `form:"repassword"`
}

type CommonResp struct {
	Msg  string `json:"msg"`
	Code string `json:"code"`
}

type LoginRequest struct {
	Email    string `form:"email"`
	Password string `form:"password"`
}

type LoginResponse struct {
	Code     string `json:"code"`
	Msg      string `json:"msg"`
	Token    string `json:"token"`
	UserName string `json:"username"`
}

type AdminLoginReq struct {
	UserName string `form:"username"`
	Password string `form:"password"`
}

type AdminLoginResponse struct {
	Code       string `json:"code"`
	Msg        string `json:"msg"`
	AdminToken string `json:"admin_token"`
	UserName   string `json:"user_name"`
}
