// Code generated by goctl. DO NOT EDIT.
package types

type SendEmailRequest struct {
	Email string `form:"email"`
}

type SendEmailResponse struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type RegisterRequest struct {
	Email      string `form:"email"`
	Captche    string `form:"catpche"`
	Password   string `form:"password"`
	Repassword string `form:"repassword"`
}

type LoginRequest struct {
	Email    string `form:"email"`
	Password string `form:"password"`
}

type LoginResponse struct {
	Code         int32  `json:"code"`
	Msg          string `json:"msg"`
	Token        string `json:"token"`
	UserName     string `json:"username"`
	AccessExpire int64  `json:"accessExpire"`
}

type AdminLoginReq struct {
	UserName string `form:"username"`
	Password string `form:"password"`
}

type AdminLoginResponse struct {
	Code         int32  `json:"code"`
	Msg          string `json:"msg"`
	AdminToken   string `json:"admin_token"`
	UserName     string `json:"user_name"`
	AccessExpire int64  `json:"accessExpire"`
}

type GetUserListReq struct {
	CurrentPage int32 `form:"currentPage,default=1"`
	PageSize    int32 `form:"pageSize,default=10"`
}

type GetUserListResponse struct {
	Code        int32  `json:"code"`
	Msg         string `json:"msg"`
	Total       int32  `json:"total"`
	FrontUsers  []User `json:"front_users"`
	CurrentPage int32  `json:"current_page"`
	PageSize    int32  `json:"page_size"`
}

type User struct {
	Email       string `json:"email"`
	Desc        string `json:"desc"`
	Status      string `json:"status"`
	CreatedTime string `json:"created_time"`
}

type SeckillReq struct {
	Id string `form:"id"`
}

type CommonReq struct {
	CurrentPage string `json:"currentPage" form:"currentPage"`
	PageSize    string `json:"pageSize" form:"pageSize"`
}

type CommonResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type GetProductListReq struct {
	CurrentPage string `form:"currentPage,default=1"`
	PageSize    string `form:"pageSize,default=10"`
}

type GetProductListResp struct {
	CommonResp
	Products    []Product `json:"products"`
	Total       int32     `json:"total"`
	CurrentPage int32     `json:"current_page"`
	PageSize    int32     `json:"page_size"`
}

type ProductAddReq struct {
	Name  string `form:"name"`
	Price string `form:"price"`
	Num   string `form:"num"`
	Uint  string `form:"uint"`
	Desc  string `form:"desc"`
}

type Product struct {
	Id         int32   `json:"id"`
	Name       string  `json:"name"`
	Price      float32 `json:"price"`
	Num        int32   `json:"num"`
	Uint       string  `json:"uint"`
	Picture    string  `json:"picture"`
	Desc       string  `json:"desc"`
	CreateTime string  `json:"create_time"`
}
